#ifndef SRC_PREFS_H_
#define SRC_PREFS_H_

#include "CompPrefs.h"

#define JOYSTICK_PORT 0
#define JOYSTICKTWO_PORT 5

#define PDP_PORT 3

#define SHOOTER_PORT 17

#define LIGHT_RING_CONTROLLER_ADDRESS 0x4

#define FRONT_RIGHT_MOVE 14
#define FRONT_LEFT_MOVE 16
#define BACK_RIGHT_MOVE 15
#define BACK_LEFT_MOVE 20

#define FRONT_RIGHT_TURN 10

#define FRONT_LEFT_TURN 13

#define BACK_RIGHT_TURN 11

#define BACK_LEFT_TURN 12

#define CHASSIS_WIDTH_BUMPERS 33.25
#define CHASSIS_LENGTH_BUMPERS 36.25

#define CHASSIS_WIDTH 23
#define CHASSIS_LENGTH 18

#endif /* SRC_PREFS_H_ */
